### ISSUE TITLE
Flags on LI / Dropdown

### ISSUE THREAD

**Issue by hugcar** [wirelab/language_switcher-plugin#10]
Can we get Flags on the switcher menu ?

I've tried to use 

`{{ languageSwitcher('li', {'toggle_title': img('theme::img/flag-'~current.language~'.png').style('width:20px;')|raw, 'container_class':'language_switcher', 'li_class':'lang', 'a_class':'lang_a'}) }}
`

but it didn't work

**Comment by ddnetters** [comment]
This repository has been deprecated, we no longer offer technical support. Sorry about that.
